### ISSUE TITLE
ImportSpec error is not handle

### ISSUE THREAD

**Issue by fabien0102** [contiamo/restful-react#99]
We should not destructure the param here -> https://github.com/contiamo/restful-react/blob/master/src/scripts/import-open-api.ts#L213

This can cause this kind of error:

```bash
> restful-react import --file ../documentation/docs/reference/api/idp.swagger.json --output src/components/queries/idp.tsx --transformer schema-transformer.js

/Users/lucasroesler/Code/contiamo/idp/ui/node_modules/restful-react/lib/bin/restful-react-import.js:249
                var openapi = _a.openapi;
                                 ^

TypeError: Cannot read property 'openapi' of undefined
    at /Users/lucasroesler/Code/contiamo/idp/ui/node_modules/restful-react/lib/bin/restful-react-import.js:249:34
    at /Users/lucasroesler/Code/contiamo/idp/ui/node_modules/call-me-maybe/index.js:13:28
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:5
```

If something we have an error, the program break before the actual error handler 😅

**Comment by TejasQ** [comment]
Fixed.

**Comment by waqas19921** [comment]
@TejasQ  still getting error in version `9.4`. There should be check on `err` object then you have to call `_a.openapi;`

```
var importSpecs = function (data, extension) {
    var schema = extension === "yaml" ? YAML.parse(data) : JSON.parse(data);
    return new Promise(function (resolve, reject) {
        if (!schema.openapi || !schema.openapi.startsWith("3.0")) {
            swagger2openapi.convertObj(schema, {}, function (err, _a) {
                var openapi = _a.openapi;
                if (err) {
                    reject(err);
                }
                else {
                    resolve(openapi);
                }
            });
        }
        else {
            resolve(schema);
        }
    });
};
```

**Comment by dbtlr** [comment]
Any word on when this will be fixed? I see that it has been addressed in master, but any word on when this will be tagged for release?

**Comment by dbtlr** [comment]
Any word on when this might be fixed? I've messed around with this a bit and found a potential solution, but I'm unsure of the downstream effects.

It seems like this is caused in the definition for [swagger2openapi.d.ts](https://github.com/contiamo/restful-react/blob/master/src/scripts/swagger2openapi.d.ts), which needs to define `data` as optional for the `convertObj` callback to be valid.

`swagger2openapi` appears to use the [call-me-maybe](https://www.npmjs.com/package/call-me-maybe) library, which follows gives the following response: 


- If promise is fulfilled, then it is called with the result of the promise: cb(null, result)
- If promise is rejected, then it is called with the rejection error: cb(err)

The downstream effect that I can predict for this is that offending block needs to look more like this, as de-structuring no longer works when you fix the interface.

```ts
      swagger2openapi.convertObj(schema, {}, (err, data) => {
        if (err) {
          reject(err);
        } else {
          resolve(data?.openapi);
        }
      });
```

I don't really like the way this looks and I'm not sure if there is any case where an `undefined` would be passed into resolve, however, in theory it would only happen on `err` anyway.

**Comment by TejasQ** [comment]
Reopening this because there’s an ongoing discussion and I don’t want it to go unaddressed. 

I’m currently a little busy for Christmas so I won’t be able to properly respond yet. 

If someone from Contiamo can respond, great. 

If not, I’m afraid we might have to deal with this in the next year.

**Comment by fabien0102** [comment]
Will try to have a look on Monday, a global advice to avoid this issue is to make sure your spec is valid (any open API linter can do the job 😉)

@dbtlr if you can provide me yours specs or some repro steps, it will help me a lot to solve this quickly 😉 (at least quicker)

**Comment by dbtlr** [comment]
Agreed, however were using specs that pass linters but still cause errors. I would say just making sure linter errors don’t cause this to error in a fatal way would be a good first step. The biggest issue seemed to be what I said, the typescript definition file seems to be wrong, in that it expects a result to always exist, except when there is an error, one does not.


~ Drew Butler

**Comment by fabien0102** [comment]
The real question is always, are yours specs really valid or the linter is failing? (I'm asking because we had the case previously, and appear that was a hole in the linter…)

Whatever, if you have a fix I will review your PR with pleasure before christmas, otherwise I will try to apply your solution on monday 😉
